apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    {{- .Values.labels | toYaml | nindent 4 }}
  name: data-exporter
spec:
  selector:
    matchLabels:
      {{- .Values.labels | toYaml | nindent 6 }}
  podMetricsEndpoints:
  - port: http
    path: /metrics
