[package]
name = "data-exporter"
version = "0.3.0"
edition = "2021"

[dependencies]
actix-rt = "2.4.0"
actix-web = "4.0.0-beta.10"
actix-web-prom = "0.6.0-beta.3"
futures = "0.3"
prometheus = { version = "0.13.0", features = ["process"] }
clap = "3.0.0-beta.5"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
jq-rs = { version = "0.4.1", features = ["bundled"] }
reqwest = "0.11"
tokio = { version = "1.14.0", features = ["full"] }
regex = "1.5"
log = "0.4"
env_logger = "0.9"
lazy_static = "1.4"
