[package]
name = "data-exporter"
version = "0.3.1"
edition = "2021"

[dependencies]
axum = "0.5"
futures = "0.3"
clap = "3.0.0-beta.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
jq-rs = { version = "0.4.1", features = ["bundled"] }
reqwest = "0.11"
tokio = { version = "1.14.0", features = ["full"] }
regex = "1.5"
log = "0.4"
env_logger = "0.9"
metrics = "0.19"
metrics-exporter-prometheus = "0.10"

[patch.crates-io]
metrics = { git = "https://github.com/fredr/metrics.git", rev = "2be80a32b10e146fcff0591b68f19d6cd244e235" }
metrics-exporter-prometheus = { git = "https://github.com/fredr/metrics.git", rev = "2be80a32b10e146fcff0591b68f19d6cd244e235" }
