probes:
- target: http://0.0.0.0:8000/file.json
  pipeline_stages:
  - name: jq
    expr: |-
      [.[] | {parent: .name} + (.children[] | {child: .name, val: .value})]
  parser: json
  metric:
    name: metric_name
    help: This is the help text
    labels:
      parent: parent
      name: child
    value: val
