metrics:
- name: metric_name
  help: This is the help text
  targets:
  - type: file
    path: examples/file.json
  pipeline_stages:
  - type: jq
    query: |-
      [.[] | {parent: .name} + (.children[] | {child: .name, val: .value})]
  parser:
    type: json
    labels:
    - parent
    - child
    value: val
- name: metric_name_constant_value
  help: This is the help text
  targets:
  - type: file
    path: examples/file.json
  pipeline_stages:
  - type: jq
    query: |-
      [.[] | {parent: .name} + (.children[] | {child: .name, val: .value})]
  parser:
    type: json
    labels:
    - parent
    - child
  value: 1
- name: github_stars
  help: Number of stars on GitHub
  targets:
  - type: http
    url: https://github.com/fredr/data-exporter/stargazers
  pipeline_stages:
  - type: regex
    pattern: (?ms:^.*All <span[^>]+>(?P<counter>\d+)</span>.*$)
    replace: |-
      {"stars": $counter, "repo": "fredr/data-exporter"}
  parser:
    type: json
    labels:
    - repo
    value: stars
