probes:
- target:
    type: file
    path: examples/file.json
  pipeline_stages:
  - jq:
      query: |-
        [.[] | {parent: .name} + (.children[] | {child: .name, val: .value})]
  parser: json
  metric:
    name: metric_name
    help: This is the help text
    labels:
      parent: parent
      name: child
    value: val
- target:
    type: http
    url: https://github.com/fredr/data-exporter/stargazers
  pipeline_stages:
  - regex:
      pattern: (?ms:^.*All <span[^>]+>(?P<counter>\d+)</span>.*$)
      replace: |-
        {"stars": $counter, "repo": "fredr/data-exporter"}
  parser: json
  metric:
    name: github_stars
    help: Number of stars on GitHub
    labels:
      repo: repo
    value: stars
